source 'https://rubygems.org'

#.env vars for secrets
gem 'dotenv-rails'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1'

# Use postgres as the database for Active Record
gem 'pg'
gem 'pg_search'

gem 'daemons'
gem 'delayed_job_active_record'

gem 'devise'
gem 'devise-async'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'foundation-rails'
gem 'foundation-icons-sass-rails'
gem 'haml-rails'


# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
#gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

gem 'haml_coffee_assets', git: "https://github.com/netzpirat/haml_coffee_assets"
gem 'execjs'


group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

gem 'annotate'

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end

group :test do
  gem 'capybara'
  gem 'poltergeist'
  gem 'simplecov', '~> 0.7.1'
#  gem 'selenium-webdriver'
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# Use unicorn as the app server
# gem 'unicorn'
gem 'passenger'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

group :development do
  gem 'capistrano',  '~> 3.1'
  gem 'capistrano-rails', '~> 1.1'
  gem 'capistrano-rvm'
  gem 'capistrano-bundler'
end

# Use debugger
# gem 'debugger', group: [:development, :test]

# Caching
#gem 'actionpack-page_caching'

# New relic monitoring
gem 'newrelic_rpm'

#spam
gem 'rakismet'
